name: Compile and push client and server to production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:server"
          file: "Dockerfile.production"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/healthchecker-server
  build-and-push-client:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          file: "Dockerfile.production"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/healthchecker-client
  notify:
    needs:
      - build-and-push-client
      - build-and-push-server
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update production
        uses: wei/curl@master
        with:
          args: https://ops.adleman4.wns.wilders.dev/hooks/update-healthchecker-production